  SELECT
    ARRAY_AGG(DISTINCT FUNDER IGNORE NULLS) AS FUNDER,
    ARRAY_AGG(DISTINCT FUNDER_ROR IGNORE NULLS) AS FUNDER_ROR,
    ARRAY_AGG(DISTINCT RECIPIENT IGNORE NULLS) AS RECIPIENT,
    ARRAY_AGG(DISTINCT RECIPIENT_ROR IGNORE NULLS) AS RECIPIENT_ROR,
    ARRAY_AGG(DISTINCT RECIPIENT_LOCATION IGNORE NULLS) AS RECIPIENT_LOCATION,
    B.oi_name AS OI,
    ARRAY_AGG(DISTINCT PI_NAME  IGNORE NULLS) AS PI_NAME,
    ANY_VALUE(START_DATE) AS START_DATE,
    ANY_VALUE(END_DATE) AS END_DATE,
    ANY_VALUE(GRANT_YEAR) AS GRANT_YEAR,
    ANY_VALUE(GRANT_DURATION) AS GRANT_DURATION,
    MAX(AMOUNT) AS AMOUNT,
    ANY_VALUE(CURRENCY) AS CURRENCY,
    MAX(AMOUNT_USD) AS AMOUNT_USD,
    ARRAY_AGG(DISTINCT SOURCE IGNORE NULLS) AS SOURCE,
    ARRAY_AGG(DISTINCT SOURCE_URL IGNORE NULLS) AS SOURCE_URL,
    GRANT_ID,
    ANY_VALUE(TITLE) AS TITLE,
    ANY_VALUE(DESCRIPTION) AS DESCRIPTION,    
    ANY_VALUE(FUNDER_PROGRAM) AS FUNDER_PROGRAM,
    CAST(NULL AS STRING) AS IP_SOLNCAT_1,
    CAST(NULL AS STRING) AS IP_SOLNCAT_2,
    CAST(NULL AS STRING) AS GRANT_CAT_1,
    CAST(NULL AS STRING) AS GRANT_CAT_2
  FROM `coki-ioi.search_terms.search_terms_wellcome20260817` AS B
    LEFT JOIN `coki-ioi.openalex_awards_2026.openalex_awards_filtered20260514` AS A 
    ON (REGEXP_CONTAINS(lower(A.DESCRIPTION), B.terms_abstract) 
        OR REGEXP_CONTAINS(lower(A.TITLE), B.terms_title)
        OR REGEXP_CONTAINS(lower(A.RECIPIENT), B.terms_recipient)
        )
  WHERE (TITLE IS NOT NULL) OR (DESCRIPTION IS NOT NULL) OR (RECIPIENT IS NOT NULL)
  GROUP BY GRANT_ID, OI
